name: Multi-Platform Matrix Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: matrix-5c8eb7b
        run: echo "Building for Python ${{ matrix.python-version }}"

      - name: Generate build artifact
        run: echo "Build output for Python ${{ matrix.python-version }}" > build_output_${{ matrix.python-version }}.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-5c8eb7b-py${{ matrix.python-version }}
          path: build_output_${{ matrix.python-version }}.txt
